Avoid to emit inline asm for WebAssembly (#5)
When I build swift code as debuggable, I got the following error:

```
error: couldn't allocate input reg for constraint 'r'
```

This means we can't use `InlineAsm` with registers because WASM doesn't have registers.
Swift uses `InlineAsm` to extend lifetime of variable for debugging. So I changed to avoid to use it.

After this change, we can build swift standard library as debuggable via `./utils/build-script --debug`.

## References
- https://gcc.gnu.org/onlinedocs/gcc/Simple-Constraints.html#Simple-Constraints